version: '3.8'


services:
  mlsecops-app:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "5000:5000"  # MLflow UI
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
      - "8080:8080"  # Airflow UI
    volumes:
      - mlflow_data:/app/mlruns  # Using a named volume for MLflow data
      - ./src:/app/src  # For hot-reloading during development
      - airflow_data:/app/airflow  # Volume for Airflow data
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - MLFLOW_ARTIFACT_ROOT=file:///app/mlruns
      - PYTHONUNBUFFERED=1
      - DOCKER_MODE=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////app/airflow/airflow.db
      - AIRFLOW__CORE__DAGS_FOLDER=/app/src/airflow/dags
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
      - AIRFLOW_ADMIN_USER=admin
      - AIRFLOW_ADMIN_PASSWORD=admin
      - AIRFLOW_ADMIN_EMAIL=admin@example.com
      - AIRFLOW_ADMIN_FIRSTNAME=Admin
      - AIRFLOW_ADMIN_LASTNAME=User
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mlsecops-network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4G"
    command: >
      bash -c "
      mkdir -p /app/airflow &&
      airflow db migrate &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin --if-not-exists &&
      airflow webserver -p 8080 & 
      airflow scheduler & 
      python src/run_all.py && 
      tail -f /dev/null"

networks:
  mlsecops-network:
    driver: bridge
    
volumes:
  mlflow_data:  # Named volume for MLflow data
  airflow_data:  # Named volume for Airflow data